base:
  data_path: /data/anapath/AprioricsSlides
  ihc_type: CD3CD20
  mapping_file: ../../../ihc_mapping.json
  mask_extension: .tif
  remote_path: /media/AprioricsSlides
  slide_extension: .svs

local:
  mask_path: masks
  main_slide_path: slides
  slide_path: slides_tmp
  geojson_path: geojsons
  log_path: registration_geojsons
  hovernet_path: hovernet_gpkgs

remote:
  mask_path: masks
  slide_path: .
  geojson_path: geojsons

slide_download:
  clean_previous: false
  import_ihc: true
  add_tree: true
  import_file: .cd3cd20

mask_extraction:
  dab_thr: 0.01
  object_min_size: 100
  binary_op: closing
  radius: 5
  nuc_min_size: 0
  nuc_max_size : 24
  num_workers: 30