stages:
  slide_download:
    cmd: >-
      python ../utils/file_transfer.py
      --out-csv .downloaded_slides.csv
      ${base}
      ${slide_download}
      --extension ${base.slide-extension}
      --rel-path ${local.slide-path}
      --remote-rel-path ${remote.slide-path}
    outs:
      - .downloaded_slides.csv:
          persist: true
    always_changed: true

  mask_extraction:
    cmd: >-
      python register_extract_polygons_masks_mp.py
      ${base}
      ${mask_extraction}
      ${local}
    deps:
      - .downloaded_slides.csv
    outs:
      - ${base.data-path}/${local.mask-path}/${base.ihc-type}:
          persist: true
      - ${base.data-path}/${local.wkt-path}/${base.ihc-type}:
          persist: true

  wkt_to_geojson:
    cmd: >-
      python ../utils/wkt2geojsons.py
      ${local}
      --data-path ${base.data-path}
      --ihc-type ${base.ihc-type}
    deps:
      - ${base.data-path}/${local.wkt-path}/${base.ihc-type}
    outs:
      - ${base.data-path}/${local.geojson-path}/${base.ihc-type}:
          persist: true

  geojson_upload:
    cmd: >-
      python ../utils/file_transfer.py
      --data-path ${base.remote-path}
      --remote-path ${base.data-path}
      --ihc-type ${base.ihc-type}
      --mapping-file ${base.mapping-file}
      --recurse
      --extension .geojson
      --rel-path ${remote.geojson-path}
      --remote-rel-path ${local.geojson-path}
      --add-tree
    deps:
      - ${base.data-path}/${local.geojson-path}/${base.ihc-type}
