base:
  data_path: /data/anapath/AprioricsSlides
  ihc_type: PHH3
  mapping_file: ../../ihc_mapping.json
  mask_extension: .tif
  remote_path: /media/AprioricsSlides
  slide_extension: .svs

local:
  mask_path: masks
  slide_path: slides
  wkt_path: wkts
  geojson_path: geojsons

remote:
  mask_path: masks
  slide_path: .
  wkt_path: wkts
  geojson_path: geojsons

slide_download:
  clean_previous: true
  import_ihc: true
  add_tree: true

mask_extraction:
  dab_thr: 0.04
  object_min_size: 50
  binary_op: none
